services:
  db:
    image: postgres:16
    container_name: futarino-kakei-db-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=futarino_kakei_db
    restart: always

  backend:
    container_name: futarino-kakei-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - go_modules:/go/pkg/mod
    environment:
      - DATABASE_URL=postgres://root:password@db:5432/futarino_kakei_db?sslmode=disable
      - GO_ENV=development
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always
    # Keep container running for development
    stdin_open: true
    tty: true

  frontend:
    container_name: futarino-kakei-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3000"
    restart: always

volumes:
  postgres_data_dev:
  go_modules:
  node_modules: 
