services:
  # フロントエンド (Next.js)
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost/api
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

  # バックエンド (Laravel)
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=futarino_kakei
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000
    volumes:
      - ./back-end:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - mysql
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Nginx (リバースプロキシ)
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./back-end/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  # MySQL データベース
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: futarino_kakei
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./back-end/database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:


networks:
  app-network:
    driver: bridge
